### PR TITLE
Metabaron1 patch 1

### PR DESCRIPTION
**Pull request by Metabaron1**
Add Postfix parameter 'relayhost' via optional environment variable RELAY_HOST

### CODE REVIEW

**Comment by arugifa** [comment]
@Metabaron1 Why do you need a relay host? Could you explain a bit more your use case? :)

**Comment by Metabaron1** [comment]
Short: Because my IP is blacklisted

Long:
Because there is an error in my ISP DNS declaration: I'm declared in a dynamic pool, so I have a static IP. And so, my IP is blacklisted by IP checker (like https://www.spamhaus.org/)  used by most official mailhost to filter spammers.
Then I can't send mail myself, and I have no choice, I have to use my ISP's relayhost to send mails.

**Review by arugifa — APPROVED** [review]
Thanks a lot for your contribution @Metabaron1 ! :rocket: :muscle: 

And sorry again for the delay: I've been quite busy recently at home :sweat_smile:

**Comment by Metabaron1** [comment]
Great! thanks :)
Np, meanwhile I was using a fork but I thought it could be usefull to other users. At least french users ;)

**Pull request merged**
